### ISSUE TITLE
Help users avoid and correct mistakes

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#157]
I think this should focus only on the aspects specific to developing, and not repeat much that we already have in designing and writing.

**Comment by iadawn** [comment]
Does this refer to the example or the content? If the content could you clarify where you feel the overlap is?

**Comment by slhenry** [comment]
"Provide clear instructions on required information formats" seems more like a writing task.

**Comment by nitedog** [comment]
Excellent tip! suggestion: "Be as forgiving of format as possible when accepting information" -> "Be as forgiving as possible when accepting user input" - also suggest using "processing" or "checking" or other rather than "accepting", but don't feel strongly about that.

Also, I suggest using only one of the two examples, possibly the phone number. I don't see the value add in two examples, except straying into details of describedby vs labelledby, which is more for the tutorials than for this resource to delve into.

**Comment by iadawn** [comment]
Copy suggestions incorporated.

I have left the two examples for the moment and will bring up the idea of removing one at EO. I think you are probably right and would suggest removing the first example. Worried that some might think the second example is too complex, but it illustrates the problem of forgiving input more than the first example.

**Comment by bakkenb** [comment]
In the first example the formatting instructions underneath the input field do not match the input field format. Is that intentional? Confusing to me. 

I also agree we could do with just the second example on this one. (nice to have two to choose from ;) )

**Comment by iadawn** [comment]
@bakkenb I am not sure I follow your concern with the first example. Instructions should be dd/MMM/YYYY... may not be relevant if the decision is to remove the first example though.

Ah. Actually I have just realised the problem. In the code I have used the HTML5 `type='date'`. In Firefox this adds nothing. In Chrome, Opera, and Safari this adds a datepicker and a format based on user locale. Unfortunately, there is no way to specify the format without using some JavaScript. If the decision is to keep this, I will see about addressing this.
