### ISSUE TITLE
Help users avoid and correct mistakes (Developing Quick Tip)

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-quick-start#233]
Could the first sentence be more direct as to what is required.

Current text:

"Help users avoid and correct mistakes

Be as forgiving of format as possible when processing user input.  For example, accept phone numbers that include spaces and delete the spaces as needed. Clearly identify errors that cannot be auto-corrected. Work with content writers to agree on content for instructions and messages."

"Help users avoid and correct mistakes

When processing user input, help users by auto-correcting their errors.  For example, accept phone numbers that include spaces and delete the spaces as needed. Clearly identify errors that cannot be auto-corrected. Work with content writers to agree on content for instructions and messages."

**Comment by James-Green** [comment]
Related to #241.  I think using the word "forgiving" helps here, maybe work it into the adjusted paragraph?

**Comment by nitedog** [comment]
Seeing this discussion, I wonder if there is a bigger mismatch between the heading and the text :(

The phrase "help users avoid and correct mistakes" comes from WCAG2 Guideline 3.3, which contains 6 Success Criteria. We link to one of those criteria in "related resources" and to a page in the tutorials explaining just one of the techniques to meet this criteria. The text finally says "Work with content writers to agree on content for instructions and messages", but that seems too subtle. I suggest the following text under that same heading:

[[
Provide clear instructions, error messages, and notifications, to help users understand interactions with your website. Also, be as forgiving of format as possible when processing user input. For example, accept phone numbers with different spacing and separator styles, to make it easier on your users.
]]

Changes:
* Kept "be as forgiving as possible" (which is also used in the tutorials) but moved it further back;
* Started the text with something more direct, and more broad to better match the title of the tip;
* Removed "clearly identify errors that cannot be auto-corrected" as it is now implied;
* Removed "work with content writers" as it is also implied. In fact, overly heavy use of the phrase "work with ..." could make the tips seem like they are only appropriate for large team with different individuals involved, whilst most tips also work for smaller development teams.

Also, I suggest linking to Guideline 3.3 rather than just individual success criteria, or to list a few more success criteria as equally related. Also link to "form instructions" and "user notifications" parts of the same tutorial, in addition to "validating input".

**Comment by iadawn** [comment]
@vmmiller, I would have medium concerns at suggesting auto-correcting as that is a bit more involved than I think what is being suggested. Which indicates what is being suggested is perhaps not clear enough :)

@nitedog, one concern I have with your suggestion is that it blurs a bit betwen writing and developing.

What I think it needs to convey:

* Don't dicate input format unless absolutely necessary
* Provide feedback that helps users identify the actual problem, e.g. date selected was in the past
* Make it easy for users to find errors and notifications, e.g. linking errors or using alerts

On that basis, I would suggest something like:

> Be as forgiving as possible when processing user input. For example, accept phone numbers with different spacing and separator styles. When errors do occur, help users by clearly indicating what the problem is, for example, 'You selected a date in the past'. Also, make finding errors and notifications easy, for example, by linking from errors in a list to the field in error.

Trying to move away slightly from the wording aspect of the tip and more about how to code something that helps avoid unnecessary errors in the first place, identify specific problems, and find where the error has occurred.

**Comment by nitedog** [comment]
This focus on format and processing is mismatch with the heading, which is much broader. One of them needs to change. I strongly suggest keeping the heading and addressing the broader issue (especially since we have the resources to support a broader scope of the tip).

**Comment by iadawn** [comment]
I am marginally leaning towards changing the title, as I think in needs to related to the specifics of developing. Might be one for further discussion?

**Comment by iadawn** [comment]
Closing with change to description in d0be6b2. Please reopen if concerns persist.
