### ISSUE TITLE
Help users avoid and correct mistakes

### ISSUE THREAD

**Issue by LydiaHarkey** [w3c/wai-quick-start#241]
The title 'Help users avoid and correct mistakes' didn't seem to fit with the other titles on the page. 

Would 'Processing User's input' work better to help the developer know what the topic is about? It seems the title 'Help users avoid and correct mistakes might work with the content 'Be as forgiving of format as possible when processing user input.'

**Comment by James-Green** [comment]
Related to #233

**Comment by nitedog** [comment]
Why does this title not fit with others on the page? "Help users avoid and correct mistakes" reads to me like "Use markup to convey meaning and structure". Maybe it is the text under the title that is throwing you off because there is a mismatch? As @James-Green points out, issue #233 seems to address this.

**Comment by iadawn** [comment]
Closing with change to description in d0be6b2. Please reopen if concerns persist.
