### ISSUE TITLE
Developing - Reflect the reading order in the code order

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-quick-start#243]
WCAG 2.0 refers to "meaningful sequence" of the code rather than comparing it to the visual presentation. Also, one could argue that the image in the example *is* presented visually before the remaining text and button. I suggest changing the text to the following:

[[
Ensure that the order of elements in the code matches the logical order of the information presented. One way to check this is to remove CSS styling and analyze the order of the content.
]]

**Comment by James-Green** [comment]
I absolutely agree with @nitedog and for everyone's convenience, this is what is there now (with his changes included): 

> Ensure that the order of elements in the code matches the logical order of the information ~~when~~ presented ~~visually~~. One way to check this is to remove CSS styling and ~~compare~~ *analyze* the order of the content ~~with the visual hierarchy of the page~~.

Visually, the shoe does appear first, but in addition to being a visual description, it's there to draw the eye and help group content.  Aside from the visual info it presents (captured in the alt), it is visually serving a similar purpose to a heading.

Screenreader users would get that all structural and grouping information from the H3 exclusively, so putting the image after the H3 is the most *meaningful* though not the *visual* sequence.

If we leave the visual references in the tip, we may be leading some people to take us literally and look for *visual* instead of *meaningful* sequence.

**Comment by iadawn** [comment]
Incorporated change with slight modification to second sentence. I felt that 'analyze' didn't necessarily help enough, as I would immediately ask the question 'analyse for what?'.

**Comment by nitedog** [comment]
I'm ok with the change from "analyze" to "review". Note that the sentence now has two "the" - "the the" rather than "that the".

**Comment by iadawn** [comment]
That is what I get for doing stuff quickly!
