### ISSUE TITLE
Is 'Keep it short and simple' too vague?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#29]
Refers to [Keep content short and simple](http://w3c.github.io/wai-quick-start/writing.html#keep-content-short-and-simple) tip in 'Writing'.

The tip had referenced the KISS ([Keep it simple, stupid](http://www.wikiwand.com/en/KISS_principle)) principle which is a common adage in design. The 'it' in this case may be too vague to be helpful?

**Comment by sharronrush** [comment]
No it is not too vague to be helpful as a "Tip."  In fact, it perfectly models what it advocates by being short and simple itself.

**Comment by melodyma** [comment]
"Keep content short and simple" it straight forward and self explanatory.

**Comment by AndrewArch** [comment]
agree

**Comment by hkramer** [comment]
Prefer "keep content short and simple"

**Comment by slhenry** [comment]
hummm.... a few points on this:
* While "it" is ambiguous, that's probably OK for the tip text, since it's explained in the explanation. [I don't feel strongly on this.]
* I think "content" is jargony in this context. Perhaps it could be "Keep writing short and simple"? [I feel medium against "content".]
* It is pretty redundant with the next point "Avoid using overly complex words and phrases". Maybe these ought to be combined , or further differentiated?
* I think this needs a qualifier -- something along the lines of "as appropriate for the context". In some cases, e.g., academic, short is not a goal. [I feel kinda strong on this point.]

/me teases Kevin on this -- we need to "eat own dog food" on with this one! -- it's kinda like tersify! ;-)

**Comment by bakkenb** [comment]
I agree with Shawn about the qualifier. Sometimes the intent of web content is not to keep it short and simple but to give very detailed information when teaching about something, for example the WCAG 2.0 page is not to be kept short and simple. 

I think we an use "Keep it Short and Simple". This is in the writing section of tips, so people should know "it" is about the writing/content of the web pages.

**Comment by schantzwebconsulting** [comment]
My initial thought is to remove this because it suggests "dumbing things down" or imposing a newspaper's editorial writing style.  Upon further reflection, I think this advice is for making all content more accessible, and should be kept.

**Comment by iadawn** [comment]
[EOWG Meeting 26 Jun](http://www.w3.org/2015/06/26-eo-minutes.html#item03): Resolved to keep a form of 'Keep content short and simple'. Further discussion lead to alternative suggestions captured in #42.

[EOWG Meeting 26 Jun](http://www.w3.org/2015/06/26-eo-minutes.html#item03): Resolved to add qualifier to initial sentence in tip to mention context.
