### ISSUE TITLE
Examples are too overwhelming

### ISSUE THREAD

**Issue by slhenry** [w3c/wai-quick-start#30]
I find the examples in <http://w3c.github.io/wai-quick-start/designing.html> attract way too much attention. I think they should be much smaller and less attention-sucking.

I think EOWG suggested that we consider adding examples *only* where they are particularly helpful. I don't think we want examples for all tips.

It would be good to get this figured out before spending any more time on examples. :-)

**Comment by iadawn** [comment]
The intention is not to provide examples for all tips. Designing and Developing (and possibly writing) will more than likely lend themselves to having more examples. I think Designing and Writing are particularly in need of examples as it is relatively easy to find/point to examples in the Tutorials for the Developing tips. There isn't that much/anything of that sort available for the other two.

**Comment by iadawn** [comment]
I have made some changes to reduce the impact of the examples. This is something I will bear in mind going forward with them. Unless there was something specific being proposed?

**Comment by slhenry** [comment]
I still feel like they are too overwhelming. My attention is sucked up by them and it's hard to focus on the text.

**Comment by AndrewArch** [comment]
to solve the distraction issue, could we have expand/contract on the examples?

**Comment by iadawn** [comment]
[EOWG Meeting 26 Jun](http://www.w3.org/2015/06/26-eo-minutes.html#item06): Resolved to explore options for show/hide of examples, and/or styling to reduce visual salience of examples.

Thoughts or examples of styling options are welcomed.

**Comment by iadawn** [comment]
Some experiments have been introduced to explore this issue:

**Comment by nitedog** [comment]
I personally like Ex2. Possibly combined with an expand/collapse feature. However, note:

* Ex1: The examples themselves take a lot of space. It is unclear to me why each example needs so much spacing and own border, which makes it cognitively heavy. Also, still not convinced that we need an example of button - it  adds more complexity than value IMO.
* Ex2: Is a pie chart really the simplest and most straight forward way to illustrate the concept of not using color alone? Otherwise, maybe the physical size and complexity of this example can be much reduced.
* Ex3: This really seems to break WAI style and introduce a font that may be more difficult to read or to accept aesthetically. I don't think it's really working to distinguish the two sections.
* Ex4: I didn't even find the button! I think this would need to be so much clearer, if we decide to implement and expand/collapse. Please please please try to reuse the existing code and styling for expand/collapse, which has been through several stages of discussion, unless there is new rationale for re-developing an existing solution (please explain in this case).

**Comment by yatil** [comment]
I like 2, imho no hide button is needed.

(Re @nitedog Ex3: It is the same font, just at a different size. Trebuchet MS is not too versatile and can look clunky at times as it was developed for old screens and not our super fancy high-dev screens. – But I agree, it doesn’t look right in this context, most likely as the font size is about the same size as the heading and the leading (“line height”) is wrong.)

**Comment by slhenry** [comment]
#1 Still has all the same issues as far as I can tell. The rust-colored border maybe gives them even more emphasis, instead of less.
#2 better than #1, but still not solving the problem. (fyi, in my setup (monitor and position), I can see the gray bar on the left, but can't quite tell that the whole thing has a different background color.)
#3 Does not help. The examples are still too big and attention-grabbing.
#4 Note that we would want a show all & hide all. I'm not convinced this is so much better than the ex-col that we've used elsewhere throughout the WAI site.

As I've said, I think a primary issue is the *size* and *colors* of these examples. 1-4 isn't addressing the fundamental problem -- they're just "lipstick on a pig" :-)

We might *also* want to do something like #2 to set them off and maybe also ex-col/show|hide -- but I still think they need tweaking to be not so overbearing.

**Comment by slhenry** [comment]
Re: "This introduced a change to the color of the Examples and Learn more headings to help reduce how these areas stand out. There is also a subtle change in the black used to be less ... black."

I strongly support them being black, not rust colored. I do not like them not really black -- it actually make them stand out more because they're a different color -- and creates [what's the visual design term when things are similar in appearance but not quite the same and it's awkward and uncomfortable?]

**Comment by hkramer** [comment]
The only example I could label as somewhat distracting is the 2nd one, the pie chart. Perhaps a background color closer to the rest of the background would address that problem. I noticed that on EasyChecks there was a distinct border around all images and the background color was lighter, usually white or close to the pinkish tone of the rest of the page. Maybe not so pastel colors for pie sections would also help. If the consensus is to allow a collapse (expand all by default), I could go along with that although I don't advocate it. As I mentioned previously, I would make those box icons solid colors in example 2. Just having the border makes it harder to determine the color.

**Comment by bakkenb** [comment]
I like that the Tips language is the only title with the maroon/rust color now. It helps set them apart as the sections on the page as the rest of the titles are black. I don't like Ex3 because the tips paragraph description text is too bold and too big. It stands out too much and pulls the emphasis back off the Tips title text.

Ex1 & Ex2 - I like #2 better as I could barely see #1 on my laptop screen unless I moved my head up and down to change the visual field.

Ex4 - I, like Eric, think that the examples should be on the page and vote to not have the show/hide option. IMO, the examples are an integral part of helping someone see a visual or "real world" demonstration of what the tip language is saying should be implemented to make a site more accessible. If the example is not integral, then it should simply not be on the page.

**Comment by vmmiller** [comment]
Ex 1 & Ex 2, with a preference for Ex. 2 (if possible, another background colour) and with the "Hide/Show".

**Comment by yatil** [comment]
I think we can slim the examples down, see [my comment](https://github.com/w3c/wai-quick-start/issues/53#issuecomment-118300237) in #53. I think that may help with this issue as well.

**Comment by iadawn** [comment]
Closing and moving discussion to #53

**Comment by slhenry** [comment]
A few things:
1. Generally I like the images much better! They are now not so attention-sucking for me. :-)
2. Instead of Alive in Wonderland examples, I [strongly] suggest using accessibility wording for the examples. Then we can reinforce the point &/or teach multiple points. e.g, see the wording in the examples at <http://www.w3.org/WAI/eval/preliminary.html#contrast> and <http://www.w3.org/WAI/eval/preliminary.html#resize>
3. "Inappropriate instruction using color only" ... "Appropriate instruction using color and symbol" -- Why not Inaccessible and Accessible?
4. In the example for "Ensure form elements include clearly associated labels" I suggest delete the required fields all together so as not to complicate the example with more than one point. Also, what about the suggestion of including option/radio buttons &/or check boxes?
5. I still suggest/request *not* to use the WAI rust color in the examples.
6. The example for "Provide clear feedback" is missing * on the Comment field label.
7. I'm still concerned with using BAD for the "responsive design" example.

**Comment by iadawn** [comment]
1. Good
1. I used non-intrusive text to reduce the cognitive load of reading about a point and seeing a point at the same time. Also, I liked the human element it brought. The example in 'interactive elements' is a little more challenging, as it needs a bit more text to balance the structure of the example. I will look into it.
1. Changed
1. Ah... I missed that as it wasn't in the resolution (or I didn't read it!). Done.
1. This is extremely challenging as in order to meet AAA contrast with the background as is, and using a red, the color is going to be extremely similar to the WAI color. Open to suggestions.
1. Actually it isn't, it is just you have a slightly zoomed view and it tucks under the text input field. I need to look at this whole structure and how it looks at lots of different levels of zoom.
1. Changed.

I am closing this issue. If there are more comments on individual examples, please raise a specific issue.
