### ISSUE TITLE
"additional resource"

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-quick-start#46]
Avoid using "additional resource" as a prefix as it is ambiguous and not helpful. In "sufficient contrast" it should probably be something like "Checker tools" or such.

**Comment by iadawn** [comment]
Ideally I would like to develop a set of clear and common terms that can be used to identify available resources within the 'Learn more' sections. This *was* a bit of a catch all as I am not sure how many similar links will be created as the tools are developed.

Ideally the terminology for the resource categorization should not be finalized until all the links are identified, then a proper set of terms can be determined.

**Comment by nitedog** [comment]
I am a consistency advocate but where there is sufficient rationale to break it, then so be it. In this case there is a unique link that will probably not appear anywhere else. This warrants an own prefix IMO.

**Comment by iadawn** [comment]
I agree that it is likely that this will be one of those outliers. I reserve the right to change it if in the fullness of time it turns out that there is another outlier similar enough to this one to share a meaningful term. Now, I have an image of two outlying links lost in the void, seeking each other to share a categorical future. The romantic in me 😉
