### ISSUE TITLE
Are the examples the simplest and most straight-forward way to illustrate the key messages of each tip?

### ISSUE THREAD

**Issue by iadawn** [w3c/wai-quick-start#53]
Examples are available for:

* [Provide sufficient contrast between colors](http://w3c.github.io/wai-quick-start/designing.html#provide-sufficient-contrast-between-colors)
* [Don't use color alone to signify meaning](http://w3c.github.io/wai-quick-start/designing.html#dont-use-color-alone-to-signify-meaning)
* [Ensure interactive elements are easy to identify](http://w3c.github.io/wai-quick-start/designing.html#ensure-interactive-elements-are-easy-to-identify)
* [Ensure form elements include clearly associated labels](http://w3c.github.io/wai-quick-start/designing.html#ensure-form-elements-include-clearly-associated-labels)
* [Provide clear feedback](http://w3c.github.io/wai-quick-start/designing.html#provide-clear-feedback)
* [Create designs for different viewport sizes](http://w3c.github.io/wai-quick-start/designing.html#create-designs-for-different-viewport-sizes)

**Comment by slhenry** [comment]
I don't think so.

* Provide sufficient contrast between colors.

I'm not convinced example(s) are helpful here. [MILD]
If we decide to have them, then I think it should be gray text on gray background -- because that's probably the most common low contrast in the wild. [MEDIUM] I also think they could be simplified quite a bit: change "Lorem ipsum dolor sit amet" to "Text with insufficient contrast" and change "Sed do eiusmod tempor incid" to "Text with sufficient contrast" (then no need for separate captions); no third example -- and make the font smaller, and less spacing around it all (including the spacing in the images themselves). [MEDIUM]

* Don't use color alone to signify meaning

The colorful charts are way too attention-grabbing. We should not use them. [HIGH]
I'm not convinced example(s) are helpful here. [MILD]
If we decide to have them, use something simple, e.g., required fields in color and with asterisks. (from WCAG: “required fields are red", “error is shown in red", and “Mary's sales are in red, Tom's are in blue") [MEDIUM]

(I'll comment on the others asap, hopefully Thur morning.)

**Comment by melodyma** [comment]
"Ensure form elements include clearly associated labels" is extreme and unrealistic. A more realistic example is when placeholder text is used as labels.

**Comment by iadawn** [comment]
Interestingly the example in 'Ensure form elements include clearly associated labels' was actually based on a [comment form I found while researching the example](http://wildwebweaving.com/2009/09/06/bad-form-design-stupid-choices/). I have emphasised the separation, but that was really all.

**Comment by hkramer** [comment]
I think examples in general are helpful (not sure if this is part of what is being asked). Some people do better with images and examples, others with text. 

Regarding specific examples:
Color contrast: I somewhat agree with Shawn - most common misuse seems to be same color on a lighter shade of the same color - often gray on lighter gray or blue on a lighter blue. I don't like that the 1st 2 examples are so similar.

"Ensure form elements include clearly associated labels" example I'm okay with the example provided.

"Don't use color alone to signify meaning" - the pie chart may be a bit complex. Something more simple might work better [mild]

**Comment by bakkenb** [comment]
Personally, I like examples. I always have, always will. They speak volumes to me, so I say leave them in and add more when/where appropriate. That being said, here are my comments.

- Contrast between Colors - Agree with Shawn about changing text and using gray.

- Color Alone - I could be wrong here, but I think most designers are now mostly aware that "required fields in red" or "errors in red" should not be the only way to indicate where information is needed anymore. I think that the example should show something more tied to page content like a bar chart or a map graphic. I don't mind the pie chart example, but I think there are other examples that could be a little more real world. ex. http://www.ict.griffith.edu.au/wiseman/DECB/map660.gif 

- Interactive Elements - On the first example, can you show plain text with the link text. The example only shows link text which makes it look like a button. On the second example, can you show an actual change of style when it is hovered over (make the example live). I like the 3rd and 4th examples as is.

- Associated Labels - I see where Melody is going with her comment. I am okay with the example that is currently on the page, but maybe we could implement something more interesting or powerful as suggested by Melody. Here is a page that explains this very well and we could use similar examples: http://www.nngroup.com/articles/form-design-placeholders/

- Clear Feedback - Typo in the first sentence of the definition. Change "when wrong" to "went wrong." Also change "really stands out" to "prominently stands out." Otherwise I like this example; simple and straight forward.

- Viewport Sizes - This one concerns me a bit. True responsive design is not a WCAG SC, but more of a business decision to properly present a site "differently" on a computer screen vs. a tablet or phone. SC 1.4.4 is not about responsive design, but about the ability to change text size of the "same" content presentation on a particular device. In other words, can the text be scaled successfully on any given device. I like this tip, but I don't think we can imply that one must/should implement responsive design to address SC 1.4.4.

**Comment by vmmiller** [comment]
I like examples - so, for me, they are positive.  

Color contrast:  Agree with Shawn

Create designs for different viewports (MEDIUM/STRONG)
-	the heading/subtitle stands out from the others.  For all the others subtitles, there is a specific link to accessibility whereas I feel, in this case, the focus is design rather than accessibility
Request:  
Could the heading be modified to make a link to resizing text.  For example, something along the lines of “Ensure text resizes according to device”
-	in my view, “responsive design” stands out more than anything else and again places the focus on design elements.  Secondly, whilst "responsive design" is current now, on the other hand, in a couple of years, it probably won’t be.  I would prefer to simply remove the first part of the sentence containing the words “Commonly called 'responsive design'” and leave the rest as is.
-     Perhaps a pronounced example of text or a web site which does not resize correctly would be a good example.

**Comment by slhenry** [comment]
* Ensure interactive elements are easy to identify

I spent a little time trying to figure out what these each were, and gave up. Part of the issue may be that the "caption" wording is inconsistent and not clear. [high]

I'm not convinced example(s) are helpful here. [mild]
* If we decide to have them, I think they should be smaller and simpler -- and probably on a white background. [high]
* The "Hovered link" looks to me like it's just changed to a visited link color. Maybe a more common and clearer example would be to leave the link text blue and have a pale background around it?[medium]
* The dotted line is too close to the text, it impedes reading. [high]

sidenote: Is it really important to "provide distinct styles for mouse hover, keyboard focus, and touch-screen activation" -- that is, each needs to be different?

**Comment by slhenry** [comment]
Ensure form elements include clearly associated labels
http://w3c.github.io/wai-quick-start/designing.html#ensure-form-elements-include-clearly-associated-labels

I agree with Melody that the bad example is extreme and unusual. I think it detracts rather than helps. [high]

I'm not convinced example(s) are helpful here. [mild]
If we keep them:
* Make the background of the form box gray. [medium]
* In the good example, I think there should be less space between the end of the labels and the start of the fields. (per "Avoid having too much distance between labels and associated elements." :-) [medium]
* Make it all smaller. (People don't need to easily read the text, just get an idea that the labels are well positioned.) [high]
* Consider including 2 option/radio buttons or checkboxes to show that different placement. [mild]
* [minor] The left alignment looks like a mistake 'cause their close but not the same. Either left-align the labels with "Add a comment", or move them over a little more right.

sidenote: "Labels are usually positioned to the left or above the element, except for checkboxes and radio buttons where it is usually to the right." Does this need clarification that it's for left-right languages? Also, I think should simply the sentence. In Easy Checks, we say "For left-to-right languages, labels should usually be: * Left of text boxes and drop-down lists. * Right of radio buttons and checkboxes."

**Comment by slhenry** [comment]
Provide clear feedback
http://w3c.github.io/wai-quick-start/designing.html#provide-clear-feedback

I think the example is useful here! ;-)

[medium] suggestions:
* Make the background of the form gray.
* I think it would be best to use a highlight color that is not so close to the WAI site <h2> color.
* "There were two problems with your submission." -> "There are two problems:"
* "The email address provided does not seem to be valid" -> "E-mail address is not valid."
* "There was no comment provided" -> "Comment field is empty. It is a required field."

[low-super-nitpicky: The highlights aren't the same on the right. ;-]

**Comment by slhenry** [comment]
Provide clear feedback
http://w3c.github.io/wai-quick-start/designing.html#provide-clear-feedback

I think the example is useful here! ;-)

[medium] suggestions:
* Make the background of the form gray.
* I think it would be best to use a highlight color that is not so close to the WAI site h2 color.
* "There were two problems with your submission." -> "There are two problems:"
* "The email address provided does not seem to be valid" -> "E-mail address is not valid."
* "There was no comment provided" -> "Comment field is empty. It is a required field."

[low-super-nitpicky: The highlights aren't the same on the right. ;-]

**Comment by slhenry** [comment]
Create designs for different viewport sizes
http://w3c.github.io/wai-quick-start/designing.html#create-designs-for-different-viewport-sizes

I think it's probably good to have an example for this one.

I don't think I like "Browser display" and "Mobile display". If I'm in a browser on my laptop and I increase the text size a lot, I get the other display. Also, if I have 3 browser windows side-by-side. [medium]

Please do not use BAD as the example web page, because the real BAD is currently not responsive. [HIGH] How about the Tutorials?

[sidenote: The text needs editing, but I'll be good and put that as a separate edit/issue -- sorry I didn't before.]

**Comment by slhenry** [comment]
Create designs for different viewport sizes
http://w3c.github.io/wai-quick-start/designing.html#create-designs-for-different-viewport-sizes

I think it's probably good to have an example for this one.

I don't like "Browser display" and "Mobile display". If I'm in a browser on my laptop and I increase the text size a lot, I get the other display. Also, if I have 3 browser windows side-by-side. [medium]

Please do not use BAD as the example web page, because the real BAD is currently not responsive. [HIGH] How about the Tutorials?

[sidenote: The text needs editing, but I'll be good and put that as a separate edit/issue -- sorry I didn't before.]

**Comment by yatil** [comment]
* [strong] I think we should not show bad examples (apart for the low-contrast one, that one is quite illustrative.

* [medium] I think the button example in [Provide sufficient contrast between colors](http://w3c.github.io/wai-quick-start/designing.html#provide-sufficient-contrast-between-colors) doesn’t show any additional information

* [medium] I like the [pie-chart example](http://w3c.github.io/wai-quick-start/designing.html#dont-use-color-alone-to-signify-meaning) in theory but maybe it should at least have a sentence on what is archived with the labels. I can also see the use of a simpler example, like what @slhenry is describing.

* [strong] The yellow-ish shadowy rounded corner style is very, very, very attention grabbing, especially in the [Ensure interactive elements are easy to identify](http://w3c.github.io/wai-quick-start/designing.html#ensure-interactive-elements-are-easy-to-identify) section where they also jump up and down for me, see:
![tips_on_designing_for_web_accessibility_ _quick_start_tips_ _wai](https://cloud.githubusercontent.com/assets/58862/8496637/17d138f0-2177-11e5-8ed6-b44c7cdb8d6d.png)
  * I think we can easily get rid of the yellow background. The figcaptions should be the same height to ensure that the images are on the same height: 
![tips_on_designing_for_web_accessibility_ _quick_start_tips_ _wai](https://cloud.githubusercontent.com/assets/58862/8496688/6f65e962-2177-11e5-8b96-795e57112434.png)
  * The first example (or all of the examples) should have surrounding text to make the point more clear.
  * [very, very mild] I wonder if it was a better idea to use neutral link text than link text that says what the example is showing…
  * I also wonder if we need to briefly describe what keyboard focus is, that is a concept that I rarely see designers to be aware of.

* [strong] [Ensure form elements include clearly associated labels](http://w3c.github.io/wai-quick-start/designing.html#ensure-form-elements-include-clearly-associated-labels) should show radiobuttons/checkboxes.
  * [mild] maybe also select boxes and fieldsets

* I really like the example in [Provide clear feedback](http://w3c.github.io/wai-quick-start/designing.html#provide-clear-feedback)

* [mild] I’m OK with using BAD in the [Create designs for different viewport sizes](http://w3c.github.io/wai-quick-start/designing.html#create-designs-for-different-viewport-sizes) example, it is clear that it is an example and people who don’t know BAD won’t get the reference and the people who know bad know that it is not responsive.

**Comment by iadawn** [comment]
## Summary of feedback

### General

* Yellow bordered box too attention grabbing, remove it (EE+++)

### Provide sufficient contrast between colors

* May not be helpful (SLH+)
* Change to grey on grey, a more common misuse (SLH++, HK, BB++)
* Remove button example (SLH, EE++, SAZ)
* Bad example and good example too similar (HK)
* Reduce negative spacing (SLH++)

### Don't use color alone to signify meaning

* Pie chart colors too attention grabbing (SLH+++)
* Pie chart may be too complex, something more simple (SLH++, HK+, EE+, SAZ)
* May not be helpful (SLH+)
* Avoid 'Required fields' type example (BB++)
* Consider bar chart or map graphic (BB++)
* Don't include bad examples (EE+++)

### Ensure interactive elements are easy to identify

* Include non-link text for contrast (BB++, EE+++)
* Show change in style on hover (BB++)
* Not sure what these are (SLH+++)
* Examples are not helpful (SLH++)
* Make the examples simpler (SLH+++)
* Change background to white (SLH+++)
* Hovered link looks like visited link color, change background color instead (SLH++)
* Dotted link too close to text (SLH+++)
* Use neutral link text to reduce confusion (EE+)

### Ensure form elements include clearly associated labels

* Bad example too extreme (MM, SLH+++)
* Example provided is ok (HK)
* Implement more interesting bad example (BB++)
* Examples are not helpful (SLH+)
* Change background of form box to gray (SLH++)
* Reduce space between label and field (SLH++)
* Make it smaller, people don't need to read text (SLH+++)
* Consider including radio or checkbox to show different positioning (SLH+, EE+++)
* Include select boxes and fieldsets (EE+)
* '[minor] The left alignment looks like a mistake 'cause their close but not the same. Either left-align the labels with "Add a comment", or move them over a little more right.' (SLH)
* Don't include bad examples (EE+++)

### Provide clear feedback

* Like it (BB, SLH, EE)
* Make form background gray (SLH++)
* Avoid using WAI Red as highlight color (SLH++)

### Create designs for different viewport sizes

* Remove SC from Learn more (BB+++)
* Example showing text resizing badly (VM++)
* Good to have an example (SLH)
* Browser display and mobile display may be misleading (SLH++)
* Don't use BAD as the example web page (SLH+++)
* Not a problem to use BAD (EE+)

**Comment by iadawn** [comment]
Closed based on extensive change. Any issues with changes made should be raised as a separate GitHub issue.
