### ISSUE TITLE
Order of Developing Tips

### ISSUE THREAD

**Issue by sharronrush** [w3c/wai-quick-start#67]
Not sure why we start with Help Users...  it seems abrupt.  I suggest this order at the top of the list: 
Use progressive enhancement
Adopt a responsive design approach
Use mark-up to convey meaning and structure
Associate all form elements with labels
Help users avoid and correct mistakes

[Medium/Strong] Rationale: Start from the general approach and get to the more specific techniques as the reader learns more and gets in the accessibility groove.

**Comment by iadawn** [comment]
Done

**Comment by slhenry** [comment]
Actually, I'd like to suggest a different approach. How about start with the easiest ones to understand and the easiest ones to implement. And then the most important ones for accessibility.

I think "Adopt a responsive design approach" and maybe even "Use progressive enhancement" are major things that could scare people away from accessibility if we start with that. Also, I think most people looking at this will already have a project underway, and so they might not be able to do much about these right away -- they'd only be useful to them on another project when they can address them before or early in the project.

**Comment by sharronrush** [comment]
Strongly disagree. Responsive design and progressive enhancement are well established design and development techniques that align accessibility with mainstream development trends. Both are widely known, immediately recognizable, even hot topics and are very easy to understand in the context of the target audience.

**Comment by slhenry** [comment]
I'll give you that they're "widely known, immediately recognizable, even hot topics". :) However, I still think they're major efforts that need to be addressed early in a project. And I think many people coming into this page will already be well into a project.

I still think we should start with the easier, smaller things. :)

**Comment by slhenry** [comment]
Another idea might be to provide some grouping to separate specific little things (like setting lang) from those big design things. In the Easy Checks TOC, we do that at  http://www.w3.org/WAI/eval/preliminary#toc (Note that the grouping is only there; we do not introduce another level of headings to the main page.)

**Comment by bakkenb** [comment]
This one is really difficult for me to comment on because this is not my area of expertise, but i will add my 2 cents.

I would start this list with the two easiest and least time consuming tips to implement. I believe doing so will "help ease readers into accessibility" when they see the first part of the list is not that difficult to accomplish and add to their normal development processes. Perhaps consider "Identify page language and language changes" and then "Associate all form elements with labels" as the first two tips.

Next I would move on to those tips that would have the largest real world impact. After reading the first two and thinking "these things are pretty easy... what else?", then they are introduced to tips that would solve the largest amount of problems with the accessibility of their site. Perhaps consider "Ensure that all interactive elements are keyboard accessible" and then "Use markup to convey meaning and structure" and then "Ensure resized text is legible" and so on...

Then move on to those that occur more often in practice.

Then close with those that are more behind the scenes like "Ensure compatibility of your code" and "Check that your code validates"

NOTE: I am not a developer, so it is hard for me to determine which tips best fit in the categories I described above. I was just trying to put some structure to the categories to lay out the tip order in.

**Comment by sharronrush** [comment]
My strong opinion based on project development experince is that before any developer gets to the point where she/he is doing even the small things, they will choose a development approach. Encouraging them to think of the big picture - a responsive, progressively enhanced approach will be important as a very first consideration.

**Comment by AndrewArch** [comment]
I have to agree with Sharron - start with the biggest issues. We don't know when a dev might read this (start/middle/end of project, so lets assume they read it at the start :)

**Comment by slhenry** [comment]
RESOLUTION from 31 July telecon <http://www.w3.org/2015/07/31-eo-minutes.html#item05>
"In general, the Tips will be ordered from easy to achieve to the more difficult, conceptual tips"

**Comment by iadawn** [comment]
Have changed the order of the tips to:

* Associate all form elements with labels
* Include alternative text for images
* Identify page language and language changes
* Use mark-up to convey meaning and structure
* Help users avoid and correct mistakes
* Reflect the reading order in the code order
* Write code that adapts to user's technology
* Ensure resized text is legible
* Provide meaning for non-standard interactive elements
* Ensure that all interactive elements are keyboard accessible
* Ensure that CAPTCHAs have accessible alternatives 

Strictly speaking this isn't the _easiest_ to the hardest, as the easiest is certainly identifying language. However, I think that does not meet the [criteria for the tips](https://www.w3.org/WAI/EO/wiki/Quick_Start_Guides/Requirements_Analysis#Criteria_for_Tips) as well as labels and images.
